# Site settings
# in the templates available like {{ site.myvariable }}.
title: Reytriever.com - Rey the Golden Retriever
email: reytriever@christoc.com
brand: Reytriever
headline: Golden Retriever
description: > # this means to ignore newlines until "baseurl:"
  Dog website!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.reytriever.com" # the base hostname & protocol for your site
copyright: 2020 Christoc.com

# Build settings
markdown: kramdown

# Account ids
snapwidget: 896917

# Contacts
email: reytriever@christoc.com
phone: 

# Tracking
googleAnalitycsID: UA-69145-54

